### ISSUE TITLE
Delete Appointment endpoint is not deleting appointments

### ISSUE THREAD

**Issue by jgondev** [ardalis/pluralsight-ddd-fundamentals#38]
I'm creating my own project based in this solution and I reached a situation that is not handled in this repo either.

Looking at the code in Endpoint/Appointment/Delete. The appointment it's just being removed from Schedule's list, but in the db this means removing the reference to the schedule in the appointment table for that particular record, not removing the record itself. 

What would be the best practice approach to achieve that? I cannot create a repository of this entity as it's not Aggregate root (required by the RepositoryBase interface)

Thanks

**Comment by ardalis** [comment]
Sounds like a bug. Let me investigate and get back with you. It *should* actually delete the record, since EF should track the change (removal from aggregate) and perform a delete based on it (not just removing the reference, which means what, setting the scheduleId to null?

Anyway I'll look into it.

**Comment by jgondev** [comment]
My bad @ardalis, in my appointment class I was missing the scheduleId property. After adding that the appointment record is being deleted as well. Thanks anyway!
